### ISSUE TITLE
javassist stopped working in JDK11 b6

### ISSUE THREAD

**Issue by sdfelts** [jboss-javassist/javassist#194]
Unsafe.defineClass was removed so the class can't be defined.

When running with javassist-3.22.0-GA.jar, it results in 
Caused By: java.lang.NullPointerException
        at javassist.util.proxy.SecurityActions.setAccessible(SecurityActions.java:103)
        at javassist.util.proxy.DefineClassHelper.toClass3(DefineClassHelper.java:151)

The quick fix to get a working jar is to remove the JDK9 logic in src/main/javassist/util/proxy/DefineClassHelper.java by removing the JAVA_9 { .... } code and
changing the logic to
ClassFile.MAJOR_VERSION >= ClassFile.JAVA_9 
            ? SecuredPrivileged.JAVA_OTHER

**Comment by AlanBateman** [comment]
Unsafe.defineClass has been terminally deprecated since JDK 9.

The Lookup.defineClass is the support way to inject proxy class into the same package/loader as another class.

**Comment by beikov** [comment]
I created a JIRA ticket for this here: https://issues.jboss.org/browse/JASSIST-271

**Comment by sdfelts** [comment]
This is fixed in 3.23.1-GA

**Comment by AlanBateman** [comment]
I assume this will break again once java.base is fully encapsulated (test with --illegal-access=deny to check this). The right way to fix this is to look a Lookup object.

**Comment by rsansores** [comment]
Hi, I'm not completely sure but it looks like the problem is not quite solved.

Using latest openjdk11:

```
# java -version
openjdk version "11-ea" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11-ea+9)
OpenJDK 64-Bit Server VM 18.9 (build 11-ea+9, mixed mode)
```

When trying to run a spring boot project with spring-data:

```
Caused by: java.lang.NullPointerException: null
	at javassist.util.proxy.DefineClassHelper$SecuredPrivileged$1.defineClass(DefineClassHelper.java:130) ~[javassist-3.23.1-GA.jar!/:na]
	at javassist.util.proxy.DefineClassHelper.toClass(DefineClassHelper.java:243) ~[javassist-3.23.1-GA.jar!/:na]
	at javassist.util.proxy.FactoryHelper.toClass(FactoryHelper.java:128) ~[javassist-3.23.1-GA.jar!/:na]
	at javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:552) ~[javassist-3.23.1-GA.jar!/:na]
	at javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:537) ~[javassist-3.23.1-GA.jar!/:na]
	at javassist.util.proxy.ProxyFactory.createClass1(ProxyFactory.java:473) ~[javassist-3.23.1-GA.jar!/:na]
	at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:444) ~[javassist-3.23.1-GA.jar!/:na]
	at org.hibernate.proxy.pojo.javassist.JavassistProxyFactory.postInstantiate(JavassistProxyFactory.java:75) ~[hibernate-core-5.2.16.Final.jar!/:5.2.16.Final]
	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactory(PojoEntityTuplizer.java:162) ~[hibernate-core-5.2.16.Final.jar!/:5.2.16.Final]
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:156) ~[hibernate-core-5.2.16.Final.jar!/:5.2.16.Final]
	at org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:58) ~[hibernate-core-5.2.16.Final.jar!/:5.2.16.Final]
	... 50 common frames omitted
```

**Comment by sdfelts** [comment]
Yes, I'm still seeing this with 3.23.1-GA

**Comment by chibash** [comment]
The problem was fixed and the fix has been committed to the master branch.

**Comment by nanachimi** [comment]
I'm also getting the same issue. Any workaround for this when using spring data with JDK 11?

**Comment by nanachimi** [comment]
I managed to get it run by updating my spring boot version from `2.0.5-RELEASE` to `2.1.0.M4`. The javassist in my classpath is `3.23.1-GA`

**Comment by chibash** [comment]
Can you try https://github.com/jboss-javassist/javassist/releases/tag/rel_3_24_0_rc  ?

**Comment by nanachimi** [comment]
I can try it only when it will be published to maven central repo. I use gradle to manage my dependencies.

**Comment by chibash** [comment]
Then wait until the GA release is available from the repo.  It will be available soon.

**Comment by nanachimi** [comment]
Okay! Thanks

**Comment by chibash** [comment]
[3.24.0-RC](https://github.com/jboss-javassist/javassist/releases/tag/rel_3_24_0_rc) is already available, so I'll release GA in a week unless I see any serious bug reports.

**Comment by chibash** [comment]
3.24.0-GA is now available from Central.

**Comment by NingZhang-Ericsson** [comment]
It is here:
http://central.maven.org/maven2/org/javassist/javassist/3.24.0-GA/

**Comment by rajiv180984** [comment]
I am using JDK version: 1.8 and when I am running application from eclipse.
I struggle d a lot with same problem . I have added the dependency and all problem solved for me.

<dependency>
    <groupId>org.javassist</groupId>
    <artifactId>javassist</artifactId>
    <version>3.23.1-GA</version>
</dependency>

**Comment by javabreaker** [comment]
Why still issue 3-27.0GA release?

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by javassist.util.proxy.SecurityActions (file:/C:/Users/XXX/.m2/repository/org/javassist/javassist/3.27.0-GA/javassist-3.27.0-GA.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)

**Comment by sdfelts** [comment]
To use the new JDK9+ API’s using a Lookup object, javassist needed to introduce a new API and applications need to use it javassist.CtClass(Class) instead of just upgrading to a new version of javassist.
Dropwizard already did this – see https://github.com/dropwizard/dropwizard/pull/2964/files
HK2 also needs to be updated.

**Comment by marshmello275** [comment]
Im trying to execute my javaassist functionality in JRE11 with latest javassist jar 3.29.2-GA. The same functionality is working in JRE8, but not working in JRE11. Any solution for it?
