### ISSUE TITLE
May be a bug for CtNewMethod.make...

### ISSUE THREAD

**Issue by lcy2008a** [jboss-javassist/javassist#43]
Not sure if this is a bug...When I wanna use CtNewMethod.make to generate a method which calls default method in interface (JDK 8 feature), it will throw a 'Class not found' exception.
Here is the test code for reproducing this error.
~~~Java
public class TestJavassist {

    public interface IA {
        default int get() {
            return 0;
        }
    }

    public static class A implements IA {
        public int anotherGet() {
            return 1;
        }
    }

    public static void main(String[] args) {
        ClassPool classPool = ClassPool.getDefault();
        try {
            CtClass ctClass = classPool.get(A.class.getName());
            String src = "public void id() { get(); }";
            CtMethod make = CtNewMethod.make(src, ctClass);
        } catch (NotFoundException e) {
            e.printStackTrace();
        } catch (CannotCompileException e) {
            e.printStackTrace();
        }
    }
}
~~~
And this is the exception:
~~~
javassist.CannotCompileException: [source error] get() not found in com.a17zuoye.commons.cache.couchbase.TestJavassist$A
	at javassist.CtNewMethod.make(CtNewMethod.java:79)
	at javassist.CtNewMethod.make(CtNewMethod.java:45)
	at com.a17zuoye.commons.cache.couchbase.TestJavassist.main(TestJavassist.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: compile error: get() not found in com.a17zuoye.commons.cache.couchbase.TestJavassist$A
	at javassist.compiler.TypeChecker.atMethodCallCore(TypeChecker.java:749)
	at javassist.compiler.TypeChecker.atCallExpr(TypeChecker.java:695)
	at javassist.compiler.JvstTypeChecker.atCallExpr(JvstTypeChecker.java:157)
	at javassist.compiler.ast.CallExpr.accept(CallExpr.java:46)
	at javassist.compiler.CodeGen.doTypeCheck(CodeGen.java:242)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:330)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351)
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50)
	at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292)
	at javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:274)
	at javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:44)
	at javassist.compiler.Javac.compileMethod(Javac.java:169)
	at javassist.compiler.Javac.compile(Javac.java:95)
	at javassist.CtNewMethod.make(CtNewMethod.java:74)
	... 7 more
~~~
It works fine if I changed the **'get();'** to **'anotherGet();'**, which is a method in class A, not in the interface. So is this a bug or I misused the 'make' method? 

Thank you in advance for your kind help.

**Comment by akutschera** [comment]
It should be a bug. The CtClass does not know the the default method from the interface.
Try this test with your interface and class:

    public void testDefaultInterfaceMethods() throws Exception {
        CtClass clazz = ClassPool.getDefault().getCtClass(A.class.getName());
        ClassFile cf = clazz.getClassFile2();
        boolean success = false;
        for (Object obj : cf.getMethods()) {
            MethodInfo methodInfo = (MethodInfo) obj;
            if (methodInfo.getName().equals("get")) {
                success = true;
            }
            if (methodInfo.getName().equals("anotherGet")) {
                System.out.println("implemented method is found");
            }
        }
        if (!success) {
            fail("default method in interface ('get') should have been found");
        }
    }

**Comment by chibash** [comment]
This is a bug reported as JASSIST-246.
It was fixed.  See https://issues.jboss.org/browse/JASSIST-246

**Comment by rcoelho6** [comment]
I update the Java Assist/Mockito Version, but still getting the same error:

 Code:
```
        ZonedDateTime zonedDate = Instant.now().atZone(ZoneOffset.systemDefault()).withHour(14).withMinute(0).withSecond(0);
        Long epoch = zonedDate.toEpochSecond();
        Instant baseInstant = Instant.ofEpochMilli(epoch);
```

Error:
```
java.lang.IllegalStateException: Failed to transform class with name br.com.tempest.d7.engine.heuristics.impl.TimeBetweenHeuristicTest. Reason: [source error] toEpochSecond() not found in java.time.ZonedDateTime
	at org.powermock.core.classloader.javassist.JavassistMockClassLoader.defineAndTransformClass(JavassistMockClassLoader.java:119)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:174)
	at org.powermock.core.classloader.MockClassLoader.loadClassByThisClassLoader(MockClassLoader.java:102)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass1(DeferSupportingClassLoader.java:147)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:98)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:154)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:47)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:107)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:69)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:36)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:31)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:24)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:29)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24)
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:49)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: javassist.CannotCompileException: [source error] toEpochSecond() not found in java.time.ZonedDateTime
	at javassist.expr.MethodCall.replace(MethodCall.java:241)
	at org.powermock.core.transformers.javassist.support.PowerMockExpressionEditor.edit(PowerMockExpressionEditor.java:102)
	at javassist.expr.ExprEditor.loopBody(ExprEditor.java:192)
	at javassist.expr.ExprEditor.doit(ExprEditor.java:91)
	at javassist.CtClassType.instrument(CtClassType.java:1431)
	at org.powermock.core.transformers.javassist.InstrumentMockTransformer.transform(InstrumentMockTransformer.java:41)
	at org.powermock.core.transformers.javassist.AbstractJavaAssistMockTransformer.transform(AbstractJavaAssistMockTransformer.java:40)
	at org.powermock.core.transformers.support.DefaultMockTransformerChain.transform(DefaultMockTransformerChain.java:43)
	at org.powermock.core.classloader.MockClassLoader.transformClass(MockClassLoader.java:184)
	at org.powermock.core.classloader.javassist.JavassistMockClassLoader.defineAndTransformClass(JavassistMockClassLoader.java:102)
	... 28 more
```

**Comment by NingZhang-e** [comment]
@rcoelho6 , could you show more code? No clue on how you used javassist from your code.
