### ISSUE TITLE
Class enhancement fails for default interface methods (Java 1.8)

### ISSUE THREAD

**Issue by brianlenz** [jboss-javassist/javassist#45]
This issue applies to the current 3.19.0-GA running on Java 8 Update 45 (1.8.0_45-b14) on OS X.

If you have a class that you are enhancing with Javassist that implements an interface with a default method implementation, Javassist enhancement fails with a VerifyError. Here's an example default method implementation on an interface:

```java
public default void foo() {

}
```

The exception goes away if you use the -noverify JVM command line option.

And here's the exception. Note that we are using Hibernate.

```
06/10/15 10:01:49 [RMI TCP Connection(3)-127.0.0.1] ERROR o.h.proxy.pojo.BasicLazyInitializer - Javassist Enhancement failed: Reply
java.lang.VerifyError: (class: Reply_$$_javassist_204, method: _d18foo signature: ()V) Illegal use of nonvirtual function call
	at java.lang.Class.getDeclaredFields0(Native Method) ~[na:1.8.0_25]
	at java.lang.Class.privateGetDeclaredFields(Class.java:2575) ~[na:1.8.0_25]
	at java.lang.Class.getField0(Class.java:2967) ~[na:1.8.0_25]
	at java.lang.Class.getField(Class.java:1693) ~[na:1.8.0_25]
	at javassist.util.proxy.ProxyFactory.setField(ProxyFactory.java:352) ~[javassist-3.11.0.GA.jar:na]
	at javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:341) ~[javassist-3.11.0.GA.jar:na]
	at javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:314) ~[javassist-3.11.0.GA.jar:na]
	at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:273) ~[javassist-3.11.0.GA.jar:na]
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.getProxyFactory(JavassistLazyInitializer.java:162) ~[hibernate-core-3.3.2.GA.jar:3.3.2.GA]
	at org.hibernate.proxy.pojo.javassist.JavassistProxyFactory.postInstantiate(JavassistProxyFactory.java:66) [hibernate-core-3.3.2.GA.jar:3.3.2.GA]
	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactory(PojoEntityTuplizer.java:188) [hibernate-core-3.3.2.GA.jar:3.3.2.GA]
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:151) [hibernate-core-3.3.2.GA.jar:3.3.2.GA]
	at org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:78) [hibernate-core-3.3.2.GA.jar:3.3.2.GA]
	at sun.reflect.GeneratedConstructorAccessor61.newInstance(Unknown Source) [na:1.8.0_25]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_25]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408) [na:1.8.0_25]
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:107) [hibernate-core-3.3.2.GA.jar:3.3.2.GA]
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructDefaultTuplizer(EntityTuplizerFactory.java:135) [hibernate-core-3.3.2.GA.jar:3.3.2.GA]
	at org.hibernate.tuple.entity.EntityEntityModeToTuplizerMapping.<init>(EntityEntityModeToTuplizerMapping.java:80) [hibernate-core-3.3.2.GA.jar:3.3.2.GA]
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:323) [hibernate-core-3.3.2.GA.jar:3.3.2.GA]
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:456) [hibernate-core-3.3.2.GA.jar:3.3.2.GA]
	at org.hibernate.persister.entity.SingleTableEntityPersister.<init>(SingleTableEntityPersister.java:131) [hibernate-core-3.3.2.GA.jar:3.3.2.GA]
	at org.hibernate.persister.PersisterFactory.createClassPersister(PersisterFactory.java:84) [hibernate-core-3.3.2.GA.jar:3.3.2.GA]
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:267) [hibernate-core-3.3.2.GA.jar:3.3.2.GA]
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1341) [hibernate-core-3.3.2.GA.jar:3.4.0.GA]
	at org.hibernate.cfg.AnnotationConfiguration.buildSessionFactory(AnnotationConfiguration.java:867) [hibernate-annotations-3.4.0.GA.jar:3.4.0.GA]
...
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4772) [catalina.jar:8.0.15]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5196) [catalina.jar:8.0.15]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.0.15]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725) [catalina.jar:8.0.15]
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701) [catalina.jar:8.0.15]
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:714) [catalina.jar:8.0.15]
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1585) [catalina.jar:8.0.15]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300) [tomcat-coyote.jar:8.0.15]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) [na:1.8.0_25]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) [na:1.8.0_25]
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:463) [catalina.jar:8.0.15]
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:413) [catalina.jar:8.0.15]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300) [tomcat-coyote.jar:8.0.15]
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819) [na:1.8.0_25]
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801) [na:1.8.0_25]
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1466) [na:1.8.0_25]
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76) [na:1.8.0_25]
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1307) [na:1.8.0_25]
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1399) [na:1.8.0_25]
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:828) [na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:323) [na:1.8.0_25]
	at sun.rmi.transport.Transport$1.run(Transport.java:178) [na:1.8.0_25]
	at sun.rmi.transport.Transport$1.run(Transport.java:175) [na:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_25]
	at sun.rmi.transport.Transport.serviceCall(Transport.java:174) [na:1.8.0_25]
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:557) [na:1.8.0_25]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:812) [na:1.8.0_25]
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:671) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_25]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_25]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
```

**Comment by metasim** [comment]
@brianlenz Did you figure out any work-around?

**Comment by brianlenz** [comment]
The only workaround I'm aware of is to not use default methods on enhanced classes :/

**Comment by galan** [comment]
Running into same issue using `io.dropwizard:dropwizard-hibernate:0.9.2`, which uses Javassist. I did override the default method, which works, but is ugly. Is Javassist going to support default methods from interfaces?

**Comment by markwoon** [comment]
Also ran into this problem when attempting bytecode enhancement with Hibernate.

Any chance this will get addressed soon?

**Comment by chibash** [comment]
So what did you all do as byte code enhancement on a default method?
Can anyone write a standalone (= without hibernate) test case?

**Comment by markwoon** [comment]
Sorry, I'm only using this via hibernate.

**Comment by chibash** [comment]
I need to know how hibernate uses Javassist when it causes this bug...
Since I'm not a developer of hibernate, it's difficult for me to guess what's going from the stack
dump above.

**Comment by chibash** [comment]
I've fixed a bug related to an default interface method.
Can anyone download javassist.jar from [master:HEAD](https://github.com/jboss-javassist/javassist) and test it with hibernate?

**Comment by beleta** [comment]
Still fails with Hibernate 3.6:

    01:14:28,564 ERROR [org.hibernate.proxy.pojo.BasicLazyInitializer] (ServerService Thread Pool -- 60)      Javassist Enhancement failed: com.carveras.candidats.model.CandidatIntern: java.lang.VerifyError: Bad invokespecial instruction: interface method reference is in an indirect superinterface.
    Exception Details:
      Location:
        com/carveras/candidats/model/CandidatIntern_$$_jvstcc7_2._d1delete()V @1: invokespecial
      Reason:
        Error exists in the bytecode
      Bytecode:
            0x0000000: 2ab7 0037 b1                           

	at java.lang.Class.getDeclaredFields0(Native Method)
	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
	at java.lang.Class.getField0(Class.java:2975)
	at java.lang.Class.getField(Class.java:1701)
	at javassist.util.proxy.ProxyFactory.setField(ProxyFactory.java:524)
	at javassist.util.proxy.ProxyFactory.createClass3(ProxyFactory.java:509)
	at javassist.util.proxy.ProxyFactory.createClass2(ProxyFactory.java:493)
	at javassist.util.proxy.ProxyFactory.createClass1(ProxyFactory.java:429)
	at javassist.util.proxy.ProxyFactory.createClass(ProxyFactory.java:400)
	at org.hibernate.proxy.pojo.javassist.JavassistLazyInitializer.getProxyFactory(JavassistLazyInitializer.java:162)
	at org.hibernate.proxy.pojo.javassist.JavassistProxyFactory.postInstantiate(JavassistProxyFactory.java:65)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.buildProxyFactory(PojoEntityTuplizer.java:185)
	at org.hibernate.tuple.entity.AbstractEntityTuplizer.<init>(AbstractEntityTuplizer.java:167)
	at org.hibernate.tuple.entity.PojoEntityTuplizer.<init>(PojoEntityTuplizer.java:77)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructTuplizer(EntityTuplizerFactory.java:105)
	at org.hibernate.tuple.entity.EntityTuplizerFactory.constructDefaultTuplizer(EntityTuplizerFactory.java:133)
	at org.hibernate.tuple.entity.EntityEntityModeToTuplizerMapping.<init>(EntityEntityModeToTuplizerMapping.java:80)
	at org.hibernate.tuple.entity.EntityMetamodel.<init>(EntityMetamodel.java:322)
	at org.hibernate.persister.entity.AbstractEntityPersister.<init>(AbstractEntityPersister.java:485)
	at org.hibernate.persister.entity.UnionSubclassEntityPersister.<init>(UnionSubclassEntityPersister.java:87)
	at org.hibernate.persister.PersisterFactory.createClassPersister(PersisterFactory.java:90)
	at org.hibernate.impl.SessionFactoryImpl.<init>(SessionFactoryImpl.java:286)
	at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1872)
	at org.springframework.orm.hibernate3.LocalSessionFactoryBean.newSessionFactory(LocalSessionFactoryBean.java:863)
	at org.springframework.orm.hibernate3.LocalSessionFactoryBean.buildSessionFactory(LocalSessionFactoryBean.java:782)
	at org.springframework.orm.hibernate3.AbstractSessionFactoryBean.afterPropertiesSet(AbstractSessionFactoryBean.java:188)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1573)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:618)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:938)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoaderListener$Proxy$_$$_WeldSubclass.configureAndRefreshWebApplicationContext(Unknown Source)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener$Proxy$_$$_WeldSubclass.initWebApplicationContext(Unknown Source)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.springframework.web.context.ContextLoaderListener$Proxy$_$$_WeldSubclass.contextInitialized$$super(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:49)
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:77)
	at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:180)
	at org.jboss.weld.probe.InvocationMonitor$InterceptorAction.proceed(InvocationMonitor.java:176)
	at org.jboss.weld.probe.InvocationMonitor$Action.perform(InvocationMonitor.java:155)
	at org.jboss.weld.probe.InvocationMonitor.monitor(InvocationMonitor.java:120)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:74)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
	at org.springframework.web.context.ContextLoaderListener$Proxy$_$$_WeldSubclass.contextInitialized(Unknown Source)
	at io.undertow.servlet.core.ApplicationListeners.contextInitialized(ApplicationListeners.java:187)
	at io.undertow.servlet.core.DeploymentManagerImpl.deploy(DeploymentManagerImpl.java:198)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:100)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)

**Comment by AndreGuima** [comment]
How can I set the -noverify JVM command line option? Is it by eclipse? Any jboss file? 
Where can I set this?
Thanks in advanced

**Comment by chibash** [comment]
-XX:+FailOverToOldVerifier

**Comment by chibash** [comment]
@beleta I've fixed another bug of ProxyFactory.  Can you try?
You can build a new jar file by:

$ ant jar

**Comment by pivolo** [comment]
Version 3.21.0-GA solved this problem in my application (hibernate 3.6)

**Comment by fenjj** [comment]
Thank @pivolo very mush！@pivolo provid very correct and useful information！Thank you very mush！
